# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-20 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20161120_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='tag1',
            field=models.ManyToManyField(related_name='dest1', to='rate.Tag'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tag2',
            field=models.ManyToManyField(related_name='dest2', to='rate.Tag'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='tag3',
            field=models.ManyToManyField(related_name='dest3', to='rate.Tag'),
        ),
    ]
