# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 09:39
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rate', '0004_auto_20161120_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.ManyToManyField(to='rate.Preference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='tag1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='tag2',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='tag3',
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='rate.Tag'),
        ),
        migrations.AddField(
            model_name='preference',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Destination'),
        ),
    ]
